from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('photos/', views.photos, name='photos'),
    path('photos/ajax/', views.photos_ajax, name='photos_ajax'),
    path('videos/', views.videos, name='videos'),
    path('videos/ajax/', views.videos_ajax, name='videos_ajax'),
    path('videos/delete/', views.delete_videos, name='delete_videos'),
    path('upload/photo/', views.upload_photo, name='upload_photo'),
    path('upload/video/', views.upload_video, name='upload_video'),
    path('photo/<int:photo_id>/', views.photo_detail, name='photo_detail'),
    path('photo/<int:photo_id>/delete/', views.delete_photo, name='delete_photo'),
    path('photo/<int:photo_id>/share/', views.share_photo, name='share_photo'),
    path('photo/<int:photo_id>/unshare/', views.unshare_photo, name='unshare_photo'),
    path('shared/photo/<uuid:token>/', views.shared_photo, name='shared_photo'),
    path('video/<int:video_id>/', views.video_detail, name='video_detail'),
    path('video/<int:video_id>/share/', views.share_video, name='share_video'),
    path('video/<int:video_id>/unshare/', views.unshare_video, name='unshare_video'),
    path('shared/video/<uuid:token>/', views.shared_video, name='shared_video'),
    path('video/<int:video_id>/delete/', views.delete_video, name='delete_video'),
    path('search/', views.search_media, name='search_media'),
    path('pay/', views.pay_for_extra_storage, name='pay_for_extra_storage'),
    path('profile/', views.profile, name='profile'),
    path('notifications/', views.notifications, name='notifications'),
    path('notifications/delete/<int:notification_id>/', views.delete_notification, name='delete_notification'),
    path('photos/delete/', views.delete_photos, name='delete_photos'),
    path('photos/download/', views.download_photos, name='download_photos'),
    path('videos/download/', views.download_videos, name='download_videos'),
    path('albums/', views.album_list, name='album_list'),
    path('albums/create/', views.album_create, name='album_create'),
    path('albums/<int:album_id>/', views.album_detail, name='album_detail'),
    path('albums/<int:album_id>/edit/', views.album_edit, name='album_edit'),
    path('albums/<int:album_id>/delete/', views.album_delete, name='album_delete'),
    path('albums/<int:album_id>/edit-contents/', views.album_edit_contents, name='album_edit_contents'),
    path('albums/<int:album_id>/reorder/', views.reorder_album_media, name='reorder_album_media'),
    path('photos/reorder/', views.reorder_photos, name='reorder_photos'),
    path('videos/reorder/', views.reorder_videos, name='reorder_videos'),
    path('albums/<int:album_id>/share/', views.share_album, name='share_album'),
    path('albums/<int:album_id>/unshare/', views.unshare_album, name='unshare_album'),
    path('shared/album/<uuid:token>/', views.shared_album, name='shared_album'),
    path('analytics/', views.storage_analytics, name='storage_analytics'),
] 