# Generated by Django 5.1.7 on 2025-06-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_paid_for_extra_storage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='storage_limit',
            field=models.BigIntegerField(default=5368709120),
        ),
    ]
