# Generated by Django 5.1.7 on 2025-06-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0002_userprofile_has_paid_for_extra_storage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='upgrade_requested',
            field=models.BooleanField(default=False),
        ),
    ]
