# Generated by Django 5.1.7 on 2025-06-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0003_userprofile_upgrade_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gmail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
