# Generated by Django 5.2.3 on 2025-06-21 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0008_userprofile_dark_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dark_mode',
        ),
    ]
