# Generated by Django 5.2.3 on 2025-06-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0011_cleanup_old_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['order', '-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['order', '-uploaded_at']},
        ),
        migrations.AddField(
            model_name='photo',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
