# Generated by Django 5.2.3 on 2025-06-21 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0011_cleanup_old_fields'),
    ]

    operations = [
        # This migration marks the state as migrated
        # The old many-to-many relationships were already removed in previous migrations
    ]
