# Generated by Django 5.2.3 on 2025-06-21 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0012_alter_photo_options_alter_video_options_and_more'),
        ('storageapp', '0013_auto_20250621_1115'),
    ]

    operations = [
    ]
