# Generated by Django 5.2.3 on 2025-06-21 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0016_add_storage_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='albums',
        ),
        migrations.RemoveField(
            model_name='video',
            name='albums',
        ),
    ]
