# Generated by Django 5.2.3 on 2025-06-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0017_remove_photo_albums_remove_video_albums'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='order',
        ),
        migrations.RemoveField(
            model_name='video',
            name='order',
        ),
    ]
