# Generated by Django 5.2.3 on 2025-06-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0018_alter_photo_options_alter_video_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['order', '-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['order', '-uploaded_at']},
        ),
        migrations.AddField(
            model_name='photo',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
